# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20171005_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='mobile',
            field=models.CharField(max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
