# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20171005_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
    ]
